### ISSUE TITLE
Enhance `data-sources` CRUD endpoints

### ISSUE THREAD

**Issue by maxachis** [Police-Data-Accessibility-Project/data-sources-app#429] opened 2024-08-29 23:11 UTC
### Context

In keeping with the changes in #417 and #390, the `/data-sources` endpoints need to be updated to enforce consistency with new standards and enhancements.

### Requirements

* Add `DELETE` endpoint to `data-source
* Update `/data-sources/ `GET` endpoint to include pagination and sorting
* Refactor other endpoints to bring them in line with new standards and enhancements

### Related
* #430 
* #419 
* [x] #431

### Tests

* Try to maintain continuity with existing tests for these endpoints

### Docs

* Swagger documentation will need to be enhanced with latest updates.

### Open questions

* What do we want to do with `/data-sources-needs-identification` and `/data-sources-map`? These can likely be consolidated with filter and column selection logic into the main endpoints (albeit at a performance cost (though perhaps not a substantial one))
* For consistency, I'd like to modify the endpoint nomenclature to bring them in line with the other endpoints -- in other words, `/data-sources-by-id/{data_source_id}` will become `/data-sources/id/{data_source_id}` and `/data-sources` will become `/data-sources/page/{page_number}`. Is this acceptable?

**Comment by maxachis** [comment] 2024-08-29 23:38
@josh-chamberlain, as before I'll need your input on the data sources permissions:

| column_name                          | STANDARD | ADMIN |
|--------------------------------------|----------|-------|
| name                                 | NONE     | NONE  |
| submitted_name                       | NONE     | NONE  |
| description                          | NONE     | NONE  |
| record_type                          | NONE     | NONE  |
| source_url                           | NONE     | NONE  |
| agency_supplied                      | NONE     | NONE  |
| supplying_entity                     | NONE     | NONE  |
| agency_originated                    | NONE     | NONE  |
| agency_aggregation                   | NONE     | NONE  |
| coverage_start                       | NONE     | NONE  |
| coverage_end                         | NONE     | NONE  |
| source_last_updated                  | NONE     | NONE  |
| detail_level                         | NONE     | NONE  |
| number_of_records_available          | NONE     | NONE  |
| size                                 | NONE     | NONE  |
| access_type                          | NONE     | NONE  |
| record_download_option_provided      | NONE     | NONE  |
| data_portal_type                     | NONE     | NONE  |
| record_format                        | NONE     | NONE  |
| update_method                        | NONE     | NONE  |
| tags                                 | NONE     | NONE  |
| readme_url                           | NONE     | NONE  |
| originating_entity                   | NONE     | NONE  |
| retention_schedule                   | NONE     | NONE  |
| airtable_uid                         | NONE     | NONE  |
| scraper_url                          | NONE     | NONE  |
| data_source_created                  | NONE     | NONE  |
| airtable_source_last_modified        | NONE     | NONE  |
| url_broken                           | NONE     | NONE  |
| submission_notes                     | NONE     | NONE  |
| rejection_note                       | NONE     | NONE  |
| last_approval_editor                 | NONE     | NONE  |
| submitter_contact_info               | NONE     | NONE  |
| agency_described_submitted           | NONE     | NONE  |
| agency_described_not_in_database     | NONE     | NONE  |
| approved                             | NONE     | NONE  |
| record_type_other                    | NONE     | NONE  |
| data_portal_type_other               | NONE     | NONE  |
| private_access_instructions          | NONE     | NONE  |
| records_not_online                   | NONE     | NONE  |
| data_source_request                  | NONE     | NONE  |
| url_button                           | NONE     | NONE  |
| tags_other                           | NONE     | NONE  |
| broken_source_url_as_of              | NONE     | NONE  |
| access_notes                         | NONE     | NONE  |
| url_status                           | NONE     | NONE  |
| approval_status                      | NONE     | NONE  |
| record_type_id                       | NONE     | NONE  |

**Comment by maxachis** [comment] 2024-08-30 00:38
@josh-chamberlain Additionally, I note a quirk in our current `/data-sources-by-id` endpoint which may need figuring out:

The `GET` method for this returns not just columns from `data_sources`, but columns from `agencies` and `data_sources_archive_info` as well. This adds a few interesting wrinkles:
1. As is, this logic violates the standard I've set for `/data-requests` and `/agencies`, where the `GET` function returns columns only from one table, and doesn't add columns from other tables. 
2. This confuses the `GET` and `POST/EDIT` logic; some of the columns returned by `GET` will not be columns that can be edited (even if only theoretically, due to access permissions` in `POST/PUT`
3. While I do see value in connecting these tables together (I would imagine many a person would want to see the names of agencies associated with data requests), these CRUD endpoints might not be the place for them.

My recommendation is to do away with the old method and maintain the one-table-per-endpoint standard I've set for `/data-requests` and `/agencies`; what do you think?

**Comment by josh-chamberlain** [comment] 2024-08-30 20:10
@maxachis

- permission table updated! Again, many of these can come through on form submissions, so they are not STANDARD but neither or they admin-only. Do we need that information somewhere?
- I added two properties that can be deprecated in v2, or now—we don't use them.
- for `url_broken`, `approved`, `records_not_online`; these should not exist at all, and are relics of old concepts that should probably have been deprecated. Those are not in Airtable or the Data Dictionary.
  - `url_broken` was replaced by `url_status`
  - `approved` was replaced by `approval_status`
  - `records_not_online` was replaced by...nothing, or maybe url status
- does `record_type_id` mean we don't need `record_type`?

Yes, it does—I would argue that agency-level properties are core to describing Data Sources, as they contain baseline information about location and jurisdiction, but that is mostly for searching, and we have an endpoint for that. You also need them on Data Source Details, and we can hit the Agencies endpoint for the info if needed. I am okay with taking your recommendation and keeping things uniform for now (i.e. only returning columns from the table).

**Comment by maxachis** [comment] 2024-08-31 20:16
> - permission table updated! Again, many of these can come through on form submissions, so they are not STANDARD but neither or they admin-only. Do we need that information somewhere?

Yes! I added a "FORM" column to indicate this, although I wonder if we should consider them to have similar logic to Data Requests owners instead and have the column be "OWNER" -- if it's the latter, that may allow me to copy more of the existing logic for data requests. 

I suppose it relates to a larger series of questions to be had over `data sources` (and `agencies`, to which this also applies): 
* Does the original submitter of these entries have any special privileges, such as the ability to edit this in the future?
* Do we want to require only signed-in users to provide these entries?
* Do we want to track which users provide which sources?

**Comment by joshuagraber** [comment] 2024-09-09 13:30
@josh-chamberlain @maxachis Some thoughts here:

> As is, this logic violates the standard I've set for /data-requests and /agencies, where the GET function returns columns only from one table, and doesn't add columns from other tables.

Well, this may mean that the DB design needs rethinking. Can't we just [associate the agency fields in the data source table with the associated agency](https://www.tutorialsteacher.com/sqlserver/tables-relations)? This would be the standard practice for dealing with such a problem, rather than having the client hit 2 endpoints and merge the responses in order to create 1 object.

> This confuses the GET and POST/EDIT logic; some of the columns returned by GET will not be columns that can be edited (even if only theoretically, due to access permissionsinPOST/PUT`

I don't think this is a problem. I've worked with plenty of APIs that have different permission structures for different methods. We can bake these entitlements into the user's table and encode them into the JWT.

> While I do see value in connecting these tables together (I would imagine many a person would want to see the names of agencies associated with data requests), these CRUD endpoints might not be the place for them.

Exactly. Relating them in the DB is the most efficient and standard solution for this.

**Comment by maxachis** [comment] 2024-09-09 14:01
@josh-chamberlain After chatting with @joshuagraber , I think he's right and it's worth pulling from a view for `GET` that includes agency-relevant info -- while clearly demarcating what are attributes from agencies and what are not. I'll think more about how that will work. 

I'll think more about the implementation on this. I'll also make a note to include @joshuagraber earlier in these conversations, so there's less changing of horses mid-stream 🐎💦

**Comment by josh-chamberlain** [comment] 2024-09-09 17:28
thank you @maxachis and @joshuagraber  for finding each other and resolving this harmoniously!

**Comment by maxachis** [comment] 2024-09-09 22:25
My intent is to work on this once @EvilDrPurple finishes a round of her #303 work. The question of how to implement nested queries with JSON while also taking variable columns (and to ensure that can be extended to other endpoint which may need this in the future as well) is a nontrivial problem. From what I've seen, SQLAlchemy may make that easier.

**Comment by EvilDrPurple** [comment] 2024-09-17 20:05
@maxachis 
> 
> ```
> {
>     "id": 1
>     "agency_id": 2
>     "name": "cat"
>     "agency": {
>         "id": 2
>         "name": "Cats Department"
>     }
> }
> ```

The only potential issue with this exact implementation is there are instances (4 to be exact) where a data source has multiple agencies attached to it. You can view them by querying the database like this:
```sql
SELECT * FROM
(
  SELECT link_id, airtable_uid, agency_described_linked_uid,
  COUNT(1)OVER(partition by airtable_uid) AS cnt
  FROM agency_source_link
)a
WHERE cnt > 1
```

**Comment by maxachis** [comment] 2024-09-18 01:16
@EvilDrPurple @josh-chamberlain 

Oooooh, that's an interesting dynamic. One possible solution is to instead have it be `agencies`, which returns the results as a list.

At the same time, maybe we don't want that if there are only 4 instances in the database where this occurs. What do you think, @josh-chamberlain ?

**Comment by EvilDrPurple** [comment] 2024-09-18 04:27
> At the same time, maybe we don't want that if there are only 4 instances in the database where this occurs.
It is likely we will add more in the future, as we find more data sources that span multiple departments, such as multi-agency investigations or regional data that lumps in many agencies

**Comment by josh-chamberlain** [comment] 2024-09-18 19:59
I can confirm that this will happen more in the future. In fact, the number would be bigger if we stopped using the `aggregated` agencies. Discussion here: https://github.com/Police-Data-Accessibility-Project/data-sources-app/issues/272

**Comment by joshuagraber** [comment] 2024-09-19 16:05
I think @maxachis's [suggestion to return an array of associated agencies](https://github.com/Police-Data-Accessibility-Project/data-sources-app/issues/429#issuecomment-2357293971) makes sense in this case. For web app purposes, we can just loop through it and render UI for each of them. And I think for anyone else using the API, the structure of the data is clear that the data is associated with / aggregated from multiple agencies.

**Comment by maxachis** [comment] 2024-09-25 21:52
In addition to the above format, we'll likely also want to include the "count" of the number of agencies returned, much as we do in typical `GET MANY` requests.

**Comment by joshuagraber** [comment] 2024-09-26 13:10
@maxachis FYI, I'm starting on the data source view, which will require agencies returned from this endpoint. Do you think you have space to prioritize this soon, or should I start with some placeholder data for now?

Also, it looks like @vikramrojo is planning (for the future) a link from this view to the data source map, centered on the source, so I'll eventually need the geolocation fields here as well. Not urgent, but while we're here I thought I'd mention it.

**Comment by maxachis** [comment] 2024-09-26 15:27
> @maxachis FYI, I'm starting on the data source view, which will require agencies returned from this endpoint. Do you think you have space to prioritize this soon, or should I start with some placeholder data for now?
> 
> Also, it looks like @vikramrojo is planning (for the future) a link from this view to the data source map, centered on the source, so I'll eventually need the geolocation fields here as well. Not urgent, but while we're here I thought I'd mention it.

Oh it's already underway: I've my main fish @EvilDrPurple working on developing it. But it may be germane to use some placeholder data for at least a little bit while we get the final kinks worked out.

**Comment by joshuagraber** [comment] 2024-09-26 17:19
Sounds good @maxachis thanks for the update!

**Comment by EvilDrPurple** [comment] 2024-09-26 18:56
@joshuagraber @maxachis 

> @maxachis FYI, I'm starting on the data source view, which will require agencies returned from this endpoint. Do you think you have space to prioritize this soon, or should I start with some placeholder data for now?

Optimistically I should have it submitted by tomorrow, so long as there are no unforeseen problems I run into

**Comment by maxachis** [comment] 2024-09-29 22:22
@joshuagraber With @EvilDrPurple's changes merged in, I can start working on this! I'm going to work into incorporating the changes described in #430 at the same time, since I'm in the area and otherwise I'll be repeating my efforts not long after this, so that will extend the time it takes to complete this, but hopefully only by a day or two.

**Closed** 2024-11-06 01:07 UTC
Labels: documentation, api, fixed_in_dev, back-end
