### ISSUE TITLE
Login enhancement: error message for creating duplicate user

### ISSUE THREAD

**Issue by josh-chamberlain** [Police-Data-Accessibility-Project/data-sources-app#218] opened 2024-03-15 16:29 UTC
We're showing an `Internal server error` when I try to create a new user with the same email. Suggesting:

> We already have an account with that email address. [Reset your password](https://data-sources.pdap.io/reset-password)

<img width="302" alt="Screen Shot 2024-03-15 at 12 25 49 PM" src="https://github.com/Police-Data-Accessibility-Project/data-sources-app/assets/30379833/95f713a6-b16c-4d5b-8517-de6fe44cc9ad">

**Comment by maxachis** [comment] 2024-06-16 17:04
While technically #306 is a duplicate of this issue, I'm closing this one because that issue is more recent and also I'm petty and vain.

**Closed by maxachis** 2024-06-16 17:04 UTC
Labels: enhancement
